[package]
name = "singlefile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ch1"
path = "ch1.rs"

[dependencies]
scan_fmt = "0.2.6"
rand = "0.8.5"
